### ISSUE TITLE
Comments cannot be included into script

### ISSUE THREAD

**Issue by eagletmt** [k0kubun/hamlit#3]
[IMO] It could be ok even if this feature isn't supported.

```haml
= 'string' # comment
```

### Expected
```
string
```

### Actual
```
/home/eagletmt/.ghq/github.com/k0kubun/hamlit/lib/hamlit/cli.rb:11:in `eval': (eval):2: syntax error, unexpected end-of-input, expecting ')' (SyntaxError)
; _buf << ("\n".freeze); _buf = _buf.join
                                         ^
        from /home/eagletmt/.ghq/github.com/k0kubun/hamlit/lib/hamlit/cli.rb:11:in `render'
        from /home/eagletmt/gems/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/eagletmt/gems/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/eagletmt/gems/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/eagletmt/gems/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/eagletmt/.ghq/github.com/k0kubun/hamlit/bin/hamlit:6:in `<top (required)>'
        from /home/eagletmt/gems/ruby/2.3.0/bin/hamlit:23:in `load'
        from /home/eagletmt/gems/ruby/2.3.0/bin/hamlit:23:in `<main>'
```

### FYI
```
% bundle exec hamlit compile in.haml
_buf = []; _buf << (('string' # comment).to_s); 
; _buf << ("\n".freeze); _buf = _buf.join
```

**Comment by k0kubun** [comment]
Thank you :dancer:
