### ISSUE TITLE
Syntax error where haml doesn't complain.

### ISSUE THREAD

**Issue by j4rs** [k0kubun/hamlit#34]
Hamlit::SyntaxError around this line:

`= render partial: "application_body", locals: {webpro: webpro, application: @application}`

```haml
        #tab-application.tab-pane{:role => "tabpanel", :class => has_messages ? "" : "active"}
          - if @application.can_rummage?
            = render partial: "application_body", locals: {webpro: webpro, application: @application}
          - else
            .field
              %h4= t("job_applications.professional_background")
```

**Comment by k0kubun** [comment]
Sorry for the delay. I understand hamlit sucks and fails to render your partial view.
Maybe `hamlit compile application_body.html.haml` contains `SyntaxError`.

But I couldn't reproduce your problem.

```sh
$ gem list | grep hamlit
hamlit (1.7.0)
$ cat a.haml
#tab-application.tab-pane{:role => "tabpanel", :class => has_messages ? "" : "active"}
  - if @application.can_rummage?
    = render partial: "application_body", locals: {webpro: webpro, application: @application}
  - else
    .field
      %h4= t("job_applications.professional_background")
$ hamlit compile a.haml
_buf = []; _buf << ("<div".freeze); _buf << (::Hamlit::Attribute.build("'", {:class=>"tab-pane",:id=>"tab-application"}, :role => "tabpanel", :class => has_messages ? "" : "active")); _buf << (">\n".freeze);
; if @application.can_rummage?;
; _buf << (::Temple::Utils.escape_html((render partial: "application_body", locals: {webpro: webpro, application: @application}))); _buf << ("\n".freeze);
; else;
; _buf << ("<div class='field'>\n<h4>".freeze);
; _buf << (::Temple::Utils.escape_html((t("job_applications.professional_background")))); _buf << ("</h4>\n</div>\n".freeze); end; _buf << ("</div>\n".freeze);
; _buf = _buf.join
```

The result does not contain SyntaxError. I guess this part of the view does not contain SyntaxError. Could you provide a snippet that generates SyntaxError from `hamlit compile`?

**Comment by j4rs** [comment]
Here's my output:

````
jars@:$ hamlit compile _application_body.haml 
/Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/old_attribute.rb:144:in `read_string!': Hamlit::SyntaxError (Hamlit::SyntaxError)
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/old_attribute.rb:134:in `read_hash_key!'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/old_attribute.rb:105:in `block in parse_old_attributes'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/old_attribute.rb:101:in `each'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/old_attribute.rb:101:in `parse_old_attributes'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/old_attribute.rb:37:in `compile_old_attribute'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/attributes.rb:55:in `block in compile_attributes'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/attributes.rb:50:in `each'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/attributes.rb:50:in `compile_attributes'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/compilers/attributes.rb:22:in `on_haml_attrs'
	from (eval):19:in `dispatcher'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:49:in `compile'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/html/dispatcher.rb:26:in `on_html_tag'
	from (eval):38:in `dispatcher'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:49:in `compile'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:7:in `block in on_multi'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:7:in `each'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:7:in `on_multi'
	from (eval):53:in `dispatcher'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:49:in `compile'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:7:in `block in on_multi'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:7:in `each'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:7:in `on_multi'
	from (eval):53:in `dispatcher'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:67:in `replace_dispatcher'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:55:in `dispatcher'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:49:in `compile'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb:45:in `call'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/engine.rb:50:in `block in call'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/engine.rb:50:in `each'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/engine.rb:50:in `inject'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/temple-0.7.6/lib/temple/engine.rb:50:in `call'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/cli.rb:41:in `generate_code'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/lib/hamlit/cli.rb:16:in `compile'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/jars/.rvm/gems/ruby-2.2.2/gems/hamlit-1.6.7/bin/hamlit:6:in `<top (required)>'
	from /Users/jars/.rvm/gems/ruby-2.2.2/bin/hamlit:23:in `load'
	from /Users/jars/.rvm/gems/ruby-2.2.2/bin/hamlit:23:in `<main>'
	from /Users/jars/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jars/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by k0kubun** [comment]
Hmm. I can think of one possibility. Do you use `{ "key": "value" }` syntax in _application_body.haml?
If so, please try hamlit v1.7.0. I've just implemented it today.

**Comment by j4rs** [comment]
I think I got it, hamlit is not supporting the new ruby 2.2.x "whatever": keyworkd style.

**Comment by k0kubun** [comment]
The feature is supported since v1.7.0.

**Comment by j4rs** [comment]
Cool ! Is working now, thanks ! 

Q: How can I render HTML? in HAML I use :preserve

**Comment by j4rs** [comment]
Oh, nice, it's working now ! thanks !

**Comment by k0kubun** [comment]
I'm very happy to hear that! :tada:

**Comment by j4rs** [comment]
I'll give a try in production and let you know about the metrics :), thanks for this gem and keep the great work up !
