### ISSUE TITLE
Cannot render multibyte char attribute

### ISSUE THREAD

**Issue by machu** [k0kubun/hamlit#8]
Hello. I tried hamlit in my project written in Japanese. But hamlit could not render multibyte character attribute.

### Source

```haml
%img{ alt: 'こんにちは' }
```

### Expected

```
<img alt='こんにちは'>
```

### Actual

```
$ gem list | grep hamlit
hamlit (0.3.2)
$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
$ hamlit render sample.haml
/Users/machu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hamlit-0.3.2/lib/hamlit/cli.rb:11:in `eval': (eval):1: syntax error, unexpected tSTRING_DEND, expecting ')' (SyntaxError)
...); _buf << ('こんにちは' }); _buf << ("'>\n".freeze);
...                               ^
(eval):2: syntax error, unexpected end-of-input, expecting ')'
; _buf = _buf.join
                  ^
        from /Users/machu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hamlit-0.3.2/lib/hamlit/cli.rb:11:in `render'
        from /Users/machu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/machu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/machu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/machu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/machu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hamlit-0.3.2/bin/hamlit:6:in `<top (required)>'
        from /Users/machu/.rbenv/versions/2.2.0/bin/hamlit:23:in `load'
        from /Users/machu/.rbenv/versions/2.2.0/bin/hamlit:23:in `<main>'
```

### FYI

```
$ hamlit compile sample.haml
_buf = []; _buf << ("<img alt='".freeze); _buf << ('こんにちは' }); _buf << ("'>\n".freeze);
; _buf = _buf.join
```

**Comment by k0kubun** [comment]
Thank you! :pray: :bow: :bow: :bow:
